language: ruby
rvm:
  - 1.9.3
before_script:
  - "bundle exec rake db:migrate"
  - "bundle exec rake db:test:prepare"
  - "bundle exec rake db:seed"
script:
  - "bundle exec rake test_with_coveralls"
notifications:
  email:
    - zhaoyan1117@berkeley.edu